name: Vehicle Suggestion
description: Create a new suggestion for what vehicle you would like to see added
labels: 
  - "assets"
  - "requested"
body:
  - type: textarea
    attributes:
      label: Details
      description: A clear and concise description of what you are suggesting.
    validations:
      required: true
